spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        show-sql: true
    h2:
        console:
            enabled: true

